from __future__ import annotations

import pandas as pd
import plotly.graph_objects as go
import streamlit as st

from auth import logout_button, require_login

require_login()
logout_button()
st.title("📈 Demand forecast")
file = st.file_uploader(
    "Upload forecast CSV (ds, product_id, yhat, yhat_lower, yhat_upper)", type=["csv"]
)
if file:
    df = pd.read_csv(file, parse_dates=["ds"])
    product = st.selectbox("Product", sorted(df.product_id.unique())) if "product_id" in df else None
    view = df[df.product_id == product] if product else df
    fig = go.Figure()
    fig.add_trace(go.Scatter(x=view.ds, y=view.yhat, name="Forecast"))
    if {"yhat_lower", "yhat_upper"}.issubset(view.columns):
        fig.add_trace(
            go.Scatter(x=view.ds, y=view.yhat_upper, line=dict(width=0), showlegend=False)
        )
        fig.add_trace(
            go.Scatter(
                x=view.ds,
                y=view.yhat_lower,
                fill="tonexty",
                line=dict(width=0),
                name="90% interval",
            )
        )
    st.plotly_chart(fig, use_container_width=True)
    st.dataframe(view, use_container_width=True)
else:
    st.info("Forecast artifacts can be generated by the training/refresh workflow and loaded here.")
